# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
domain: nuuskamummu.github.io       # Optional in this context, but can be included
url: https://nuuskamummu.github.io  # The base hostname and protocol for your site
baseurl: /Sqlite3_partitioner/      # The subpath of your site, e.g., /repository-name/
repository: nuuskamummu/Sqlite3_partitioner # for github-metadata
title: Sqlite3 Timeseries Partitioner
email: tom@rosenlundsit.se
description: This dynamic loadable library built with Rust for SQLite3 enables automatic time series partitioning based on an user specified interval. Open source project released under Apache 2.0.

aux_links:
  "Sqlite3_partitioner on GitHub":
    - "//github.com/nuuskamummu/Sqlite3_partitioner/"

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
